import { SettingsWindow } from "./settings_window.slint";
import { ResizeWindow } from "./resize_window.slint";
import { Theme } from "./theme.slint";
import { Palette, Button } from "std-widgets.slint";
import { IconDisplay, IconSet } from "@lucide";

component MenuButton inherits Rectangle {
    in-out property text <=> _txt.text;
    callback clicked <=> _touch.clicked;

    border-color: Theme.border-color;
    border-radius: 4px;
    border-width: 1px;
    height: 28px;
    preferred-width: 100%;
    background: _touch.pressed ? Theme.tool-button-background : _touch.has-hover ? Theme.tool-button-background : Theme.background;

    _txt := Text {
        color: _touch.pressed ? Theme.secondary-foreground : Theme.foreground;
        x: 30px;
        font-size: 1rem;
        vertical-alignment: center;
    }
    _touch := TouchArea { }
}

component Tooltip inherits Rectangle {
    in-out property text <=> _txt.text;

    background: Theme.background;
    border-radius: 4px;
    border-width: 1px;
    border-color: Theme.border-color;
    height: 20px;
    width: _txt.preferred-width + 10px;

    _txt := Text {
        color: Theme.foreground;
        font-size: 12px;
    }
}

component ToolButton inherits Rectangle {
    in property icon <=> _icon.icon;
    in-out property text <=> _tip.text;
    //in-out property tipz <=> _tip.z;
    in property <bool> active: false;
    callback clicked <=> _touch.clicked;

    border-radius: 4px;
    border-width: 1px;
    border-color: _touch.has-hover ? Theme.tool-button-border-color : Theme.menu-bar-background;
    width: 30px;
    height: 30px;
    background: _touch.has-hover ? Theme.tool-button-background : Theme.menu-bar-background;

    _touch := TouchArea {
        _icon := IconDisplay {
            stroke: active ? Theme.accent-color : Theme.tool-button-color;
            size: 24px;
            stroke-width: 2;
        }
    }
    _tip := Tooltip {
        x: 0px;
        //y: parent.height - 20px;
        y: parent.height + 5px;
        //z: 1;
        opacity: 0;
        visible: false;
    }
    // states [
    //     hovered when _touch.has-hover : {
    //         _tip.opacity: 1;
    //         _tip.visible: true;
    //         in { animate _tip.opacity { duration: 150ms; delay: 300ms; } }
    //     }
    // ]
}

export component AppWindow inherits Window {
    init => {
        // IconSettings.default-size = 24px; // Planned for future availability
    }
    icon: @image-url("../../res/icons/icon.png");
    title: root.window_title;
    min-width: 640px;
    min-height: 360px;
    preferred-width: 1280px;
    preferred-height: 720px;
    always-on-top: root.always_on_top_enabled;
    full-screen: root.fullscreen_enabled;
    background: Theme.background;

    in-out property <image> image_display;
    in-out property <string> window_title: "Voutil";
    in-out property <string> status_text: "Ready";
    in-out property <string> info_text: "";
    in-out property <int> current_image_index: -1;
    in-out property <int> total_images: 0;

    // --- Properties for manual pan and zoom ---
    in-out property <int> image_x: 0;
    in-out property <int> image_y: 0;
    in-out property <int> image_w: 1;
    in-out property <int> image_h: 1;
    in-out property <float> image_scale: 1.0;

    // --- Property to control layout mode ---
    in-out property <bool> auto_fit: true;
    in-out property <bool> always_on_top_enabled: false;
    in-out property <bool> fullscreen_enabled: false;
    in-out property <bool> zen_mode_enabled: false;
    in-out property <bool> show_status_messages: true;
    in-out property <bool> thumbnail_window_is_visible: false;

    // --- Internal state for dragging ---
    private property <bool> _is_dragging: false;
    private property <bool> _is_right_down: false;
    private property <bool> _is_right_dragging: false;
    private property <bool> _selection_was_active: false;
    in-out property <bool> zen_mode_before_enter: false;
    private property <int> _last_mouse_pos_x: 0;
    private property <int> _last_mouse_pos_y: 0;
    private property <int> _right_click_start_x: 0;
    private property <int> _right_click_start_y: 0;

    // --- Icon properties ---
    // private property <brush> _status_bar_color: Theme.status-bar-color;

    // --- Menu bar properties ---
    // private property <length> _menu_bar_height: Theme.menu-bar-height;
    // private property <brush> _menu_bar_background: Theme.menu-bar-background;

    // --- Resize Dialog properties ---
    in-out property <int> resize_dialog_original_w;
    in-out property <int> resize_dialog_original_h;
    in-out property <int> resize_dialog_new_w;
    in-out property <int> resize_dialog_new_h;
    in-out property <string> resize_dialog_unit: "Pixels";
    in-out property <bool> resize_dialog_lock_aspect;
    in-out property <string> resize_dialog_interpolation;

    // --- Selection properties ---
    in-out property <bool> selection_visible: false;
    in-out property <float> selection_x;
    in-out property <float> selection_y;
    in-out property <float> selection_w;
    in-out property <float> selection_h;
    in-out property <bool> is_light_border: true;
    in-out property <brush> selection_border_color: #FFFFFF80;
    in-out property <string> cursor_handle_type: "default";
    in-out property <MouseCursor> current_cursor: MouseCursor.default;

    // --- Callback functions ---
    callback request_open_file();
    callback exit();
    callback reset_view();
    callback show_settings_window();
    callback tick(bool);
    callback zoom_image(float, float, float);
    callback view_one_to_one();
    callback copy_to_clipboard();
    callback paste_from_clipboard();
    callback scale_changed(float);
    callback show_resize_window();
    callback resize_confirmed();
    callback show_color_correction_window();
    callback rotate_right();
    callback flip_horizontal();
    callback previous_image();
    callback next_image();
    callback show_thumbnail_window();
    callback pointer_event(string, string, float, float);
    callback check_selection_hit(float, float) -> bool;
    callback crop_in_place();
    callback show_custom_menu();
    callback save_as();
    callback browse_to_file_location();
    callback shortcut_pressed(string, bool, bool, bool) -> bool;

    public function show_resize() {
        root.show_resize_window();
        resize_window.setup();
        resize_window.show();
    }

    function get-cursor-from-type(handle_type: string) -> MouseCursor {
        if (handle_type == "move") { return MouseCursor.move; }
        else if (handle_type == "ns-resize") { return MouseCursor.ns-resize; }
        else if (handle_type == "ew-resize") { return MouseCursor.ew-resize; }
        else if (handle_type == "nwse-resize") { return MouseCursor.nwse-resize; }
        else if (handle_type == "nesw-resize") { return MouseCursor.nesw-resize; }
        else { return MouseCursor.default; }
    }

    // --- Timer for dynamic resize/move handling --- 
    timer := Timer {
        interval: 16ms; // Approx. 60fps
        triggered => {
            root.tick(root.auto_fit);
            self.restart(); // Use restart() to repeat the timer
        }
    }

    public function update_image_info() {
        if (root.auto_fit) {
            apply_auto_fit_properties()
        } else {
            let image_w: int = root.image_display.width;
            let image_h: int = root.image_display.height;
            let scale: float = root.image_scale;
            root.image_w = Math.round(image_w * scale);
            root.image_h = Math.round(image_h * scale);
        }
    }

    function apply_auto_fit_properties() {
        if (root.image_display.width > 0 && root.image_display.height > 0) {
            let image_w: int = root.image_display.width;
            let image_h: int = root.image_display.height;

            let container_w: int = image_container.width / 1px;
            let container_h: int = image_container.height / 1px;

            let scale_w: float = container_w / image_w;
            let scale_h: float = container_h / image_h;
            let calculated_scale: float = min(scale_w, scale_h);

            if (calculated_scale >= 1.0) {
                // Image fits without downscaling, treat as 1:1 view
                apply_view_one_to_one_properties();
           } else {
                // Image is larger than the container, scale it down
                let new_image_w: float = image_w * calculated_scale;
                let new_image_h: float = image_h * calculated_scale;
                
                root.image_scale = calculated_scale;
                root.image_w = Math.round(new_image_w);
                root.image_h = Math.round(new_image_h);
                root.image_x = Math.round((container_w - new_image_w) / 2);
                root.image_y = Math.round((container_h - new_image_h) / 2);
            }
        }
    }

    public function apply_view_one_to_one_properties() {
        let container_w: int = image_container.width / 1px;
        let container_h: int = image_container.height / 1px;

        // Calculate the new position to keep the center of the image in the center of the container
        let new_image_w: int = root.image_display.width;
        let new_image_h: int = root.image_display.height;

        root.image_scale = 1.0;
        root.image_x = Math.round((container_w - new_image_w) / 2);
        root.image_y = Math.round((container_h - new_image_h) / 2);
        root.image_w = root.image_display.width;
        root.image_h = root.image_display.height;
    }

    forward-focus: key_handler;
    key_handler := FocusScope {
        key-pressed(event) => {
            if (root.shortcut_pressed(event.text, event.modifiers.control, event.modifiers.alt, event.modifiers.shift)) {
                return accept;
            }
            reject
        }
    }

    VerticalLayout {
        spacing: 0;
        menu_bar := Rectangle {
            height: root.zen_mode_enabled ? 0px : Theme.menu-bar-height;
            background: Theme.menu-bar-background;

            main_menu := PopupWindow {
                x: 5px;
                y: Theme.menu-bar-height;
                width: 200px;
                Rectangle {
                    background: Theme.background;
                    border-width: 1px;
                    border-radius: 5px;
                    border-color: Theme.border-color;
                    drop-shadow-color: #00000050;
                    drop-shadow-blur: 10px;
                    drop-shadow-offset-x: 2px;
                    drop-shadow-offset-y: 2px;
                    VerticalLayout {
                        padding: 2px;
                        Rectangle {
                            background: #282828; // Darker background for the menu itself
                            border-radius: 4px;
                            preferred-width: 100%;
                            height: 140px; // 28 * 5
                            VerticalLayout {
                                MenuButton {
                                    text: @tr("Copy");
                                    clicked => { root.copy_to_clipboard(); main_menu.close(); }
                                }
                                MenuButton {
                                    text: @tr("Paste");
                                    clicked => { root.paste_from_clipboard(); main_menu.close(); }
                                }
                                MenuButton {
                                    text: @tr("Save as...");
                                    clicked => { root.save_as(); main_menu.close(); }
                                }
                                MenuButton {
                                    text: @tr("Preferences");
                                    clicked => { root.show_settings_window(); main_menu.close(); }
                                }
                                MenuButton {
                                    text: @tr("Quit");
                                    clicked => { root.exit(); main_menu.close(); }
                                }
                            }
                        }
                    }
                }
            }

            selection_context_menu := PopupWindow {
                x: ta.mouse-x;
                y: ta.mouse-y + menu_bar.height;
                width: 200px;
                Rectangle {
                    background: #282828;
                    border-width: 1px;
                    border-radius: 5px;
                    border-color: #454545;
                    drop-shadow-color: #00000050;
                    drop-shadow-blur: 10px;
                    drop-shadow-offset-x: 2px;
                    drop-shadow-offset-y: 2px;
                    VerticalLayout {
                        padding: 2px;
                        Rectangle {
                            background: #282828; // Darker background for the menu itself
                            border-radius: 4px;
                            preferred-width: 100%;
                            height: 84px; // 28 * 3
                            VerticalLayout {
                                MenuButton {
                                    text: @tr("Invert border color");
                                    clicked => {
                                        root.selection_border_color = root.is_light_border ? #00000080 : #FFFFFF80;
                                        root.is_light_border = !root.is_light_border;
                                        selection_context_menu.close();
                                    }
                                }
                                MenuButton {
                                    text: @tr("Preferences");
                                    clicked => { root.show_settings_window(); selection_context_menu.close(); }
                                }
                                MenuButton {
                                    text: @tr("Crop");
                                    clicked => { root.crop_in_place(); selection_context_menu.close(); }
                                }
                            }
                        }
                    }
                }
            }

            image_context_menu := PopupWindow {
                x: ta.mouse-x;
                y: ta.mouse-y + menu_bar.height;
                width: 200px;
                Rectangle {
                    background: #282828;
                    border-width: 1px;
                    border-radius: 5px;
                    border-color: #454545;
                    drop-shadow-color: #00000050;
                    drop-shadow-blur: 10px;
                    drop-shadow-offset-x: 2px;
                    drop-shadow-offset-y: 2px;
                    VerticalLayout {
                        padding: 2px;
                        Rectangle {
                            background: #282828;
                            border-radius: 4px;
                            preferred-width: 100%;
                            height: 84px; // 28 * 3
                            VerticalLayout {
                                MenuButton {
                                    text: @tr("Reset view");
                                    clicked => { root.reset_view(); image_context_menu.close(); }
                                }
                                MenuButton {
                                    text: @tr("Preferences");
                                    clicked => { root.show_settings_window(); image_context_menu.close(); }
                                }
                                MenuButton {
                                    text: @tr("Browse to file location");
                                    clicked => { root.browse_to_file_location(); image_context_menu.close(); }
                                }
                            }
                        }
                    }
                }
            }

            HorizontalLayout {
                padding: 5px;
                alignment: start;
                spacing: 4px;

                ToolButton {
                    icon: IconSet.Menu;
                    text: "Main menu";
                    //tipz: 10;
                    clicked => { main_menu.show(); }
                }
                ToolButton {
                    icon: IconSet.Folder;
                    text: "Open file";
                    clicked => { root.request_open_file(); }
                }
                ToolButton {
                    icon: IconSet.Maximize;
                    active: root.fullscreen_enabled;
                    text: "Full Screen";
                    clicked => { root.fullscreen_enabled = !root.fullscreen_enabled; }
                }
                ToolButton {
                    icon: IconSet.ArrowUpFromLine;
                    active: root.always_on_top_enabled;
                    text: "Always on top";
                    clicked => { root.always_on_top_enabled = !root.always_on_top_enabled; }
                }
            }

            HorizontalLayout {
                padding: 5px;
                alignment: center;
                spacing: 4px;

                ToolButton {
                    //icon: IconSet.Grid3x3;
                    icon: IconSet.LayoutGrid;
                    text: "Show thumbnail";
                    clicked => { root.show_thumbnail_window(); }
                }
                ToolButton {
                    //icon: IconSet.Move;
                    icon: IconSet.SquareSquare;
                    text: "Reset view";
                    clicked => { root.reset_view(); }
                }
                ToolButton {
                    icon: IconSet.SquareEqual;
                    text: "View 1:1";
                    clicked => {
                        apply_view_one_to_one_properties();
                        root.view_one_to_one();
                    }
                }
                ToolButton {
                    icon: IconSet.ChevronLeft;
                    text: "Previous image";
                    clicked => { root.previous_image(); }
                }
                ToolButton {
                    icon: IconSet.ChevronRight;
                    text: "Next image";
                    clicked => { root.next_image(); }
                }
            }

            HorizontalLayout {
                padding: 5px;
                alignment: end;
                spacing: 4px;

                ToolButton {
                    icon: IconSet.FlipHorizontal2;
                    text: "Flip horizontal";
                    clicked => {
                        root.flip_horizontal();
                    }
                }
                ToolButton {
                    //icon: IconSet.RotateCw;
                    icon: IconSet.RotateCwSquare;
                    text: "Rotate right";
                    clicked => {
                        root.rotate_right();
                    }
                }
                ToolButton {
                    icon: IconSet.Palette;
                    text: "Color correction";
                    clicked => {
                        root.show_color_correction_window();
                    }
                }
                ToolButton {
                    icon: IconSet.Scaling;
                    text: "Resize";
                    clicked => {
                        root.show_resize();
                    }
                }
            }
        }

        // Main Image Area
        image_container := Rectangle {
            background: Theme.image-container-background;
            clip: true;

            img_element := Image {
                source: root.image_display;
                x: root.auto_fit ? Math.round((parent.width - self.width) / 2 / 1px) * 1px : root.image_x * 1px;
                y: root.auto_fit ? Math.round((parent.height - self.height) / 2 / 1px) * 1px : root.image_y * 1px;
                width: root.auto_fit ? min(parent.width, root.image_display.width * 1px) : root.image_display.width * root.image_scale * 1px;
                height: root.auto_fit ? min(parent.height, root.image_display.height * 1px) : root.image_display.height * root.image_scale * 1px;
                image-fit: root.auto_fit ? contain : fill;
            }

            selection_rect := Rectangle {
                visible: root.selection_visible;
                x: root.selection_x * 1px;
                y: root.selection_y * 1px;
                width: root.selection_w * 1px;
                height: root.selection_h * 1px;
                // background: transparent;
                border-width: 1px;
                border-color: Theme.selection-border;
                background: Theme.selection-background;
                HorizontalLayout {
                    Text {
                        font-size: 13px;
                        text: Math.round(root.selection_w / root.image_scale) + " x "
                            + Math.round(root.selection_h / root.image_scale);
                        vertical-alignment: center;
                        horizontal-alignment: center;
                        color: root.is_light_border ? #FFFFFF : #000000;
                    }
                }
            }

            ta := TouchArea {
                mouse-cursor: get-cursor-from-type(root.cursor_handle_type);

                double-clicked => {
                    if (!root.auto_fit) {
                        root.reset_view();
                    } else {
                        // Current mouse in image coordinates at current scale
                        let mouse_img_x = (ta.mouse-x / 1px - root.image_x) / root.image_scale;
                        let mouse_img_y = (ta.mouse-y / 1px - root.image_y) / root.image_scale;

                        root.auto_fit = false;
                        root.image_scale = 1.0;
                        root.image_w = root.image_display.width;
                        root.image_h = root.image_display.height;
                        
                        // Set image_x/y such that the point that was under the mouse stays there at 1:1 scale
                        root.image_x = Math.round(ta.mouse-x / 1px - mouse_img_x);
                        root.image_y = Math.round(ta.mouse-y / 1px - mouse_img_y);
                        
                        root.view_one_to_one();
                    }
                }

                pointer-event(event) => {
                    if (event.kind == PointerEventKind.down) {
                        let is_on_selection = root.check_selection_hit(ta.mouse-x / 1px, ta.mouse-y / 1px);
                        if (event.button == PointerEventButton.left) {
                            if (is_on_selection) {
                                root.pointer_event("down", "left", ta.mouse-x / 1px, ta.mouse-y / 1px);
                            } else {
                                _is_dragging = true;
                                _last_mouse_pos_x = ta.mouse-x / 1px;
                                _last_mouse_pos_y = ta.mouse-y / 1px;
                            }
                        } else if (event.button == PointerEventButton.right) {
                            _is_right_down = true;
                            _selection_was_active = root.selection_visible;
                            _right_click_start_x = ta.mouse-x / 1px;
                            _right_click_start_y = ta.mouse-y / 1px;
                            root.pointer_event("down", "right", ta.mouse-x / 1px, ta.mouse-y / 1px);
                        }
                    } else if (event.kind == PointerEventKind.up) {
                        if (event.button == PointerEventButton.left) {
                            _is_dragging = false;
                            root.pointer_event("up", "left", ta.mouse-x / 1px, ta.mouse-y / 1px);
                        } else if (event.button == PointerEventButton.right) {
                            root.pointer_event("up", "right", ta.mouse-x / 1px, ta.mouse-y / 1px);
                            let is_on_selection = root.check_selection_hit(ta.mouse-x / 1px, ta.mouse-y / 1px);
                            
                            let dist_x = Math.abs(ta.mouse-x / 1px - _right_click_start_x);
                            let dist_y = Math.abs(ta.mouse-y / 1px - _right_click_start_y);
                            let is_small_drag = dist_x < 10 && dist_y < 10;

                            if (is_on_selection && !_is_right_dragging) {
                                selection_context_menu.show();
                            } else if (!_selection_was_active && (!_is_right_dragging || is_small_drag)) {
                                image_context_menu.show();
                            }
                            _is_right_down = false;
                            _is_right_dragging = false;
                        }
                    } else if (event.kind == PointerEventKind.move) {
                        if (_is_right_down) {
                            _is_right_dragging = true;
                        }
                        if (_is_dragging) {
                            if (root.auto_fit) {
                                root.auto_fit = false;
                                apply_auto_fit_properties();
                                scale_changed(root.image_scale);
                            }
                            image_x += ta.mouse-x / 1px - _last_mouse_pos_x;
                            image_y += ta.mouse-y / 1px - _last_mouse_pos_y;
                        }
                        root.pointer_event("move", "none", ta.mouse-x / 1px, ta.mouse-y / 1px);
                        _last_mouse_pos_x = ta.mouse-x / 1px;
                        _last_mouse_pos_y = ta.mouse-y / 1px;
                    }
                }
                scroll-event(event) => {
                    if (root.auto_fit) {
                        root.auto_fit = false;
                        apply_auto_fit_properties();
                        scale_changed(root.image_scale);
                    }
                    root.zoom_image(event.delta-y / 1px, ta.mouse-x / 1px, ta.mouse-y / 1px);
                    return accept;
                }
            }
        }
        status_bar := Rectangle {
            height: root.zen_mode_enabled ? 0px : Theme.status-bar-height;
            background: Theme.status-bar-background;
            HorizontalLayout {
                padding: 5px;
                padding-left: 10px;
                padding-right: 10px;
                if (root.show_status_messages) : Text {
                    font-size: 13px;
                    text: root.status_text;
                    vertical-alignment: center;
                    color: Theme.status-bar-color;
                }
                Rectangle { horizontal-stretch: 1; } // Spacer
                Text {
                    font-size: 13px;
                    text: root.info_text;
                    vertical-alignment: center;
                    color: Theme.status-bar-color;
                }
                if (root.total_images > 0) : Text {
                    font-size: 13px;
                    text: " | " + (root.current_image_index + 1) + " / " + root.total_images;
                    vertical-alignment: center;
                    color: Theme.status-bar-color;
                }
            }
        }
    }

    // Instantiate the component
    resize_window := ResizeWindow {
        original_w <=> root.resize_dialog_original_w;
        original_h <=> root.resize_dialog_original_h;
        new_w <=> root.resize_dialog_new_w;
        new_h <=> root.resize_dialog_new_h;
        unit <=> root.resize_dialog_unit;
        lock_aspect <=> root.resize_dialog_lock_aspect;
        interpolation <=> root.resize_dialog_interpolation;

        ok_clicked_resize => {
            root.resize_confirmed();
            key_handler.focus();
        }
        cancel_clicked_resize => {
            key_handler.focus();
        }
    }
}
