import { Slider, Button, GroupBox, Palette } from "std-widgets.slint";
import { Theme } from "./theme.slint";

export component ColorCorrectionWindow inherits Window {
    title: "Color Corrections";
    width: 952px;
    height: 754px;
    background: Theme.background;
    default-font-size: 14px;

    callback apply();
    callback cancel();
    callback reset();
    callback values-changed();
    callback shortcut_pressed(string, bool, bool, bool) -> bool;

    in-out property <image> original-image;
    in-out property <image> preview-image;

    in-out property <float> brightness: 0.0;
    in-out property <float> contrast: 0.0;
    in-out property <float> gamma: 100.0;
    in-out property <float> red: 0.0;
    in-out property <float> green: 0.0;
    in-out property <float> blue: 0.0;
    in-out property <float> saturation: 0.0;

    in-out property <bool> focus-trigger: false;

    private property<int> min-value: -100;
    private property<int> max-value: 100;

    forward-focus: key_handler;
    key_handler := FocusScope {
        property <bool> _trigger: root.focus-trigger;
        changed _trigger => {
            brightness_slider.focus();
        }

        key-pressed(event) => {
            if (event.text == Key.Escape) {
                root.shortcut_pressed(event.text, false, false, false);
                return accept;
            }
            if (root.shortcut_pressed(event.text, event.modifiers.control, event.modifiers.alt, event.modifiers.shift)) {
                return accept;
            }
            reject
        }

        GridLayout {
            padding: 10px;
            spacing: 10px;
            HorizontalLayout { // Preview Area
                col: 0;
                row: 0;
                colspan: 2;
                alignment: space-around;
                VerticalLayout {
                    Text {
                        text: "Original";
                        color: Theme.foreground;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        height: 25px;
                    }
                    Rectangle {
                        width: 450px;
                        height: 450px;
                        Image {
                            source: root.original-image;
                            width: 450px;
                            height: 450px;
                            image-fit: contain;
                        }
                    }
                }
                VerticalLayout {
                    Text { 
                        text: "Preview";
                        color: Theme.foreground;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        height: 25px;
                    }
                    Rectangle {
                        width: 450px;
                        height: 450px;
                        Image {
                            source: root.preview-image;
                            width: 450px;
                            height: 450px;
                            image-fit: contain;
                        }
                    }
                }
            }

            VerticalLayout { // Row 0, Column 1
                col: 0;
                row: 1;
                alignment: start;
                Rectangle{
                    border-width: 1px;
                    border-radius: 5px;
                    border-color: Theme.border-color;
                    horizontal-stretch: 1;
                    width: 460px;
                    GroupBox {
                        title: "Brightness / Contrast / Gamma";
                        horizontal-stretch: 1;
                        VerticalLayout {
                            spacing: 5px;
                            HorizontalLayout {
                                Text { text: "Brightness:"; width: 80px;
                                    color: Theme.foreground;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                                brightness_slider := Slider {
                                    width: 300px;
                                    minimum: min-value;
                                    maximum: max-value;
                                    value <=> root.brightness;
                                    changed(val) => { root.values-changed(); }
                                }
                                Text {
                                    text: round(root.brightness);
                                    color: Theme.foreground;
                                    min-width: 40px;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                            }
                            HorizontalLayout {
                                Text { text: "Contrast:"; width: 80px;
                                    color: Theme.foreground;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                                Slider {
                                    width: 300px;
                                    minimum: min-value;
                                    maximum: max-value;
                                    value <=> root.contrast;
                                    changed(val) => { root.values-changed(); }
                                }
                                Text {
                                    text: round(root.contrast);
                                    color: Theme.foreground;
                                    min-width: 40px;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                            }
                            HorizontalLayout {
                                Text { text: "Gamma:"; width: 80px;
                                    color: Theme.foreground;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                                Slider {
                                    width: 300px;
                                    minimum: 10;
                                    maximum: 500;
                                    value <=> root.gamma;
                                    changed(val) => { root.values-changed(); }
                                }
                                Text {
                                    text: round(root.gamma)/ 100.0;
                                    color: Theme.foreground;
                                    min-width: 40px;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                            }
                        }
                    }
                }
            }

            VerticalLayout { // Row 1, Column 1
                col: 1;
                row: 1;
                alignment: start;
                Rectangle{
                    border-width: 1px;
                    border-radius: 5px;
                    border-color: Theme.border-color;
                    horizontal-stretch: 1;
                    width: 460px;
                    GroupBox {
                        title: "Color Balance";
                        horizontal-stretch: 1;
                        VerticalLayout {
                            spacing: 5px;
                            HorizontalLayout {
                                Text { text: "Red:"; width: 80px;
                                    color: Theme.foreground;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                                Slider {
                                    width: 300px;
                                    minimum: min-value;
                                    maximum: max-value;
                                    value <=> root.red;
                                    changed(val) => { root.values-changed(); }
                                    }
                                Text {
                                    text: round(root.red);
                                    color: Theme.foreground;
                                    min-width: 40px;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                            }
                            HorizontalLayout {
                                Text { text: "Green:"; width: 80px;
                                    color: Theme.foreground;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                                Slider {
                                    width: 300px;
                                    minimum: min-value;
                                    maximum: max-value;
                                    value <=> root.green;
                                    changed(val) => { root.values-changed(); }
                                }
                                Text {
                                    text: round(root.green);
                                    color: Theme.foreground;
                                    min-width: 40px;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                            }
                            HorizontalLayout {
                                Text { text: "Blue:"; width: 80px;
                                    color: Theme.foreground;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                                Slider {
                                    width: 300px;
                                    minimum: min-value;
                                    maximum: max-value;
                                    value <=> root.blue;
                                    changed(val) => { root.values-changed(); }
                                }
                                Text {
                                    text: round(root.blue);
                                    color: Theme.foreground;
                                    min-width: 40px;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                            }
                        }
                    }
                }
            }

            VerticalLayout { // Row 0, Column 2
                col: 0;
                row: 2;
                alignment: start;
                Rectangle{
                    border-width: 1px;
                    border-radius: 5px;
                    border-color: Theme.border-color;
                    horizontal-stretch: 1;
                    width: 460px;
                    GroupBox {
                        title: "Saturation";
                        horizontal-stretch: 1;
                        VerticalLayout {
                            spacing: 5px;
                            HorizontalLayout {
                                Text { text: "Saturation:"; width: 80px;
                                    color: Theme.foreground;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                                Slider {
                                    width: 300px;
                                    minimum: min-value;
                                    maximum: max-value;
                                    value <=> root.saturation;
                                    changed(val) => { root.values-changed(); }
                                }
                                Text {
                                    text: round(root.saturation);
                                    color: Theme.foreground;
                                    min-width: 40px;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                    height: 20px;
                                }
                            }
                        }
                    }
                }
            }

            HorizontalLayout { // Buttons
                col: 0;
                row: 3;
                colspan: 2;
                alignment: end;
                spacing: 10px;
                Button { text: "OK"; clicked => { root.apply(); } }
                Button { text: "Cancel"; clicked => { root.cancel(); } }
                Button { text: "Reset"; clicked => { root.reset(); } }
            }
        }
    }
}
