import { ScrollView, Palette } from "std-widgets.slint";
import { Theme } from "./theme.slint";

export struct Thumbnail {
    source: image,
    path: string,
}

export component ThumbnailWindow inherits Window {
    title: "Thumbnails";
    min-width: 210px;
    min-height: 210px;
    preferred-width: 210px;
    preferred-height: 600px;
    background: Theme.background;

    in property <[Thumbnail]> thumbnails;
    in-out property <string> selected-path;
    in-out property <int> selected-index: -1;
    in-out property <bool> wrap-folder: true;
    changed selected-index => { root.ensure_visible(); }

    callback hide();
    callback thumbnail_clicked(string);
    callback next_image();
    callback previous_image();
    callback move_selection(int);
    callback ensure_visible();
    callback shortcut_pressed(string, bool, bool, bool) -> bool;

    private property <length> thumb-size: 100px;
    private property <length> spacing: 10px;
    private property <int> columns: Math.floor(root.width / (thumb-size + spacing));
    changed columns => { root.ensure_visible(); }
    private property <int> rows: Math.ceil(root.thumbnails.length / root.columns);

    ensure_visible => {
        if (root.selected-index < 0) { return; }
        
        let row = Math.floor(root.selected-index / root.columns);
        let item_y_min = root.spacing + row * (root.thumb-size + root.spacing);
        let item_y_max = item_y_min + root.thumb-size + root.spacing;
        
        // Check if the item is above the visible area
        if (item_y_min < -sv.viewport-y) {
            sv.viewport-y = -item_y_min;
        } 
        // Check if the item is below the visible area
        else if (item_y_max > -sv.viewport-y + sv.height) {
            sv.viewport-y = -(item_y_max - sv.height);
        }
    }

    forward-focus: key_handler;
    key_handler := FocusScope {
        key-pressed(event) => {
            if (root.shortcut_pressed(event.text, event.modifiers.control, event.modifiers.alt, event.modifiers.shift)) {
                return accept;
            }
            if (event.text == Key.Escape || event.text == "T" || event.text == "t") {
                root.hide();
                return accept;
            }
            let len = root.thumbnails.length;
            if (len <= 0) { return reject; }

            if (event.text == Key.LeftArrow || event.text == "A" || event.text == "a") {
                let next_idx = root.selected-index - 1;
                if (next_idx < 0) {
                    if (root.wrap-folder) {
                        root.selected-index = len - 1;
                    }
                } else {
                    root.selected-index = next_idx;
                }
            } else if (event.text == Key.RightArrow || event.text == "D" || event.text == "d") {
                let next_idx = root.selected-index + 1;
                if (next_idx >= len) {
                    if (root.wrap-folder) {
                        root.selected-index = 0;
                    }
                } else {
                    root.selected-index = next_idx;
                }
            } else if (event.text == Key.UpArrow || event.text == "W" || event.text == "w") {
                root.selected-index = Math.max(0, root.selected-index - root.columns);
            } else if (event.text == Key.DownArrow || event.text == "S" || event.text == "s") {
                root.selected-index = Math.min(len - 1, root.selected-index + root.columns);
            }
            
            accept // Consume event
        }
        key-released(event) => {
            if (root.selected-index >= 0 && root.selected-index < root.thumbnails.length) {
                root.thumbnail_clicked(root.thumbnails[root.selected-index].path);
            }
            accept
        }
    }

    sv := ScrollView {
        viewport-height: root.rows * (root.thumb-size + root.spacing) + root.spacing;
        Rectangle {
            width: 100%;
            height: 100%;
            for thumb[i] in root.thumbnails : _touch := TouchArea {
                width: root.thumb-size;
                height: root.thumb-size;
                x: root.spacing + Math.mod(i, root.columns) * (root.thumb-size + root.spacing);
                y: root.spacing + Math.floor(i / root.columns) * (root.thumb-size + root.spacing);
                Rectangle {
                    border-width: (i == root.selected-index) ? 2px : 1px;
                    border-color: (i == root.selected-index) ? Theme.accent-color : (_touch.has-hover ? Theme.tool-button-border-color : Theme.border-color);
                    background: _touch.pressed ? Theme.tool-button-background : _touch.has-hover ? Theme.tool-button-background : Theme.background;
                    Image {
                        source: thumb.source;
                        width: 92%;
                        height: 92%;
                        image-fit: contain;
                    }
                }
                clicked => { 
                    root.thumbnail_clicked(thumb.path);
                    root.selected-index = i;
                }
                double-clicked => {
                    root.thumbnail_clicked(thumb.path);
                    root.selected-index = i;
                    root.hide();
                }
            }
        }
    }
}
