on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]

name: Check Windows
jobs:
  check:
    strategy:
      matrix:
        # FIXME: Enable legacy windows if required
        # os: [windows-latest, windows-2019]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - uses: Swatinem/rust-cache@v2

      - name: Install Ninja
        run: choco install ninja

      - name: cargo check without default features
        run: cargo check --no-default-features --features notan/shaderc

      - name: cargo build
        run: cargo build
