on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]

name: Check ARM
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Update Rust
        run: rustup update

      - name: Install cargo cross
        run: cargo install cross

      - name: Cross-compile arm
        run: cross check --target armv7-unknown-linux-gnueabihf --no-default-features --features notan/glsl-to-spirv

      - name: Check output
        run: ls target/
